#######################################################################
#   日志                                                               #
#######################################################################
# 界面日志最大缓冲行
view.logger.buffer = 1000



#######################################################################
#   代理                                                               #
#######################################################################
# 代理配置 https://find.xiaoxiongip.com/find_http?key=30e10213cc4f1deb&count=1&type=text&only=1&province=1014&city=1049&textSep=1&pw=no&updateWhite=yes
proxy.key = 30e10213cc4f1deb
proxy.province = 2429




#######################################################################
#   调度                                                               #
#######################################################################
# 分为4个阶段提价
schedule.segment = 4
# 阶段间隔时间，单位ms
schedule.segment.sleep = 10000
# 每个阶段最大4个线程
schedule.nThread = 4
# 线程内每个任务执行间隔时间，单位ms
schedule.nThread.sleep = 1000

