#######################################################################
#   日志                                                               #
#######################################################################
# 界面日志最大缓冲行
view.logger.buffer = 1000



#######################################################################
#   代理                                                               #
#######################################################################
# 代理配置 https://find.xiaoxiongip.com/find_http?key=30e10213cc4f1deb&count=1&type=text&only=1&province=1014&city=1049&textSep=1&pw=no&updateWhite=yes
proxy.key = 30e10213cc4f1deb
proxy.province = 2429


#######################################################################
#   调度                                                               #
#######################################################################
# 问卷间隔时间（单位：ms）
schedule.survey.segment = 10000-20000
# 问卷提交时间（单位：ms）
schedule.survey.submit = 10000-20000